update

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -111,7 +111,16 @@ jobs:
           kubectl config set-context --current --namespace=storeapp || echo "No context set, checking available contexts."
           kubectl cluster-info || echo "Failed to connect to the Kubernetes API server"
 
+      #Linting, YAML syntax check to catch issues before deployment
+      - name: Validate Kubernetes Manifests
+        run: kubectl apply --dry-run=client -f appstore.yaml
+
       # Deploy to Kubernetes
       - name: Deploy to Kubernetes
         run: |
-          kubectl apply -f appstore.yaml || echo "Failed to apply *.yaml"
+          kubectl apply -f appstore.yaml || echo "Failed to apply appstore.yaml"
+
+      # Automatic Rollback on Failure
+      - name: Rollback on failure
+        if: failure()
+        run: kubectl rollout undo deployment storeapp -n storeapp
