update

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -108,23 +108,8 @@ jobs:
         run: |
           kubectl config set-context --current --namespace=storeapp || echo "No context set, checking available contexts."
           kubectl cluster-info || echo "Failed to connect to the Kubernetes API server"
-      
-      # Configure envsubst
-      - name: Install envsubst
-        run: sudo apt-get install gettext-base
-       
-      # Substitute secret values
-      - name: Substitute values
-        env:
-          $ACR_NAME: ${{ secrets.ACR_NAME }} 
-          $RABBITMQ_USER: ${{ secrets.RABBITMQ_USER }}
-          $RABBITMQ_PASS: ${{ secrets.RABBITMQ_PASS }}
-          $ORDER_QUEUE_USER: ${{ secrets.ORDER_QUEUE_USER }}
-          $ORDER_QUEUE_PASS: ${{ secrets.ORDER_QUEUE_PASS }}
-        run: |
-          envsubst < appstore.yaml > deploywithsecrets.yaml
 
       # Deploy to Kubernetes
       - name: Deploy to Kubernetes
         run: |
-          kubectl apply -f deploywithsecrets.yaml || echo "Failed to apply *.yaml"
+          kubectl apply -f appstore.yaml || echo "Failed to apply *.yaml"
